# Generated by Django 3.1.5 on 2021-06-18 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('incident_department', models.CharField(choices=[('CH', 'Corporate Headoffice'), ('OD', 'Operations Department'), ('WS', 'Work Station'), ('MD', 'Marking Division')], max_length=2)),
                ('description', models.CharField(max_length=250)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('incident_location', models.TextField()),
                ('severity', models.CharField(choices=[('M', 'Mild'), ('MD', 'Moderate'), ('S', 'Severe'), ('F', 'Fetal')], max_length=10)),
                ('cause', models.TextField()),
                ('actions', models.TextField()),
                ('type_env', models.CharField(max_length=10)),
                ('type_inju', models.CharField(max_length=10)),
                ('type_property', models.CharField(default='f', max_length=10)),
                ('type_vehicle', models.CharField(default='f', max_length=10)),
                ('reportedby_id', models.IntegerField()),
            ],
        ),
    ]
