# Generated by Django 3.1.5 on 2021-06-18 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='reportedby_id',
            field=models.CharField(max_length=10),
        ),
    ]
